### ISSUE TITLE
Combine 'get' and 'list' command into one single command

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-commander#166]
I think 'get' and 'list' could be combined into one single 'get' command.
by default it would return an js-object if you request only one instance (like the current 'get') and it would return a list of objects if you request multiple instances (like the current 'list').
an additional optional parameter (like '--as-list') could be added if you want also a list of objects as result even if you request only a single object.
Examples:
`lisky get delegates cc001` -> {...}
`lisky get delegates cc001 lightcurve` -> [{..}, {...}]
`lisky get delegates cc001 --as-list` -> [{...}]

**Comment by shuse2** [comment]
Superseded by #522.
When refactoring the commands, get and list will be combined.
