### ISSUE TITLE
Add a pre-commit-msg hook to set relevant emoji

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-commander#300]
Right now we're typing quite long emoji names manually in commit messages. Better would be a script which asked you what kind of commit it was, and automatically added the right emoji.

**Comment by willclarktech** [comment]
Might be helpful: https://stackoverflow.com/a/10015707

**Comment by neuromusic** [comment]
see also https://github.com/tjoskar/gitmoji-commit-hook

**Comment by willclarktech** [comment]
@neuromusic Nice! This also looks like the kind of thing that can be adopted by developers unilaterally rather than having to change the code base, if I'm not mistaken.

**Comment by shuse2** [comment]
Closing due to no further activity
