### ISSUE TITLE
Show warning when passphrase is not recommended format

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-commander#337]
https://github.com/LiskHQ/lisky/pull/328#discussion_r150211401

In line with this comment it would be nice to validate passphrase inputs (or not if a `--no-verify` flag is passed). The user should be given all the relevant error messages.

This should be done at the end of the `getInputsFromSources` util function.

**Comment by shuse2** [comment]
We should not reject the command but print the warning
