### ISSUE TITLE
Use Vorpal's chalk and strip-ansi capabilities

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-commander#395]
Right now we use `chalk` and `strip-ansi` directly, but Vorpal already exposes `vorpal.chalk` and `vorpal.chalk.stripColor`. If we used these instead we could remove two of our direct dependencies.

**Comment by Tosch110** [comment]
Nice catch!

**Comment by shuse2** [comment]
This will be invalid as we move away from vorpal in `v2.0`
