### ISSUE TITLE
Add option to create multiple accounts

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-commander#423]
### Description

Sometimes it would be helpful to create multiple accounts in one go. E.g. if setting up a third-party application which needs to distinguish between payments from different sources.

**Expected behavior:** `create account -n 50` would create 50 accounts and return them in an array

**Actual behavior:** Only one account can be created at a time

**Comment by willclarktech** [comment]
@Mastermaulik For table output they should be separate rows in the same table.

**Comment by Mastermaulik** [comment]
@willclarktech , I was able to create n number of accounts through code.

Here is what updated code looks like:

```
export const actionCreator = () => async ({ options }) => {
	const {
		number = 1,
	} = options;

	const accountsArray = [];

	for (let i = 0; i < number; i += 1) {
		const passphrase = createMnemonicPassphrase();
		const { privateKey, publicKey } = cryptography.getKeys(passphrase);
		const { address } = cryptography.getAddressFromPublicKey(publicKey);
		accountsArray.push({
			passphrase,
			privateKey,
			publicKey,
			address,
		});
	}

	return accountsArray;
};
```
The output of the commands looks like:

<img width="1280" alt="screen shot 2018-05-03 at 2 10 38 pm" src="https://user-images.githubusercontent.com/5520612/39567201-cc7766b4-4edb-11e8-811f-ed327c598173.png">

If this looks ok, I can send a pull request.
