### ISSUE TITLE
Refactor exec file to use streams

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-commander#427]
**Expected behavior:** Lisky should be able to handle large script files smoothly. Streams would be a natural choice.

**Actual behavior:** Lisky synchronously loads the whole file, splits it into lines, and processes this array all at once.

**Comment by shuse2** [comment]
Since we move away from vorpal at `v2.0`, this will be invalid

**Comment by willclarktech** [comment]
@shuse2 This issue is actually unrelated to vorpal since the `exec` function was written outside that framework. I'm not sure we need it though.

**Comment by shuse2** [comment]
Ah this is `exec` file on the root folder!
then my comment is invalid 😢 
but i don't think we need to re-implement the `exec` feature. It will be more useful and be able to create more feature just by directly using the shell script =0
