### ISSUE TITLE
Add commands for node maintenance

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-commander#441]
This may or may not require additional functionality from Lisk Elements.
- [x] Node health (testnet, latest block, peers) #507 
- [x] Enable forging #510

**Comment by Mastermaulik** [comment]
@shuse2 and @willclarktech , can you please provide details about what the commands for these tasks will look like? 

Also please provide what should we use from API Client of Lisk-Element to get response for each command.

**Comment by shuse2** [comment]
These commands are mostly wrappers for
```
elements.APIClient().node.xxx()
```
but we havn't decided what command will make sense with other commands existing.

**Comment by Mastermaulik** [comment]
@shuse2 , when I am trying to execute command 

`getAPIClient().node.getConstants()`

I get the following error message:
`PopsicleError: Unhandled response type: text/html`

The request that lisk-elements is trying to send is:
```
{ method: 'GET',
  url: 'https://node01.lisk.io:443/api/node/constants',
  headers:
   { Accept: 'application/json',
     'Content-Type': 'application/json',
     nethash: 'ed14889723f24ecc54871d058d98ce91ff2f973192075c0155ba2b7b70ad2511',
     'User-Agent': '????/???? (????) LiskJS/1.0 (+https://github.com/LiskHQ/lisk-js) darwin 17.2.0; x64; en_US.UTF-8' } }
```

**Comment by shuse2** [comment]
```
set api.network beta
```
if you run this command, you will be able to connect to open beta network with the commander

**Comment by Mastermaulik** [comment]
@shuse2  Run the above command in the console, and then make the request?

I did that and got the same result.

**Comment by Mastermaulik** [comment]
I was able to get a response by doing this.

Now, to talk about these tasks, should we have them as different commands?
Like: get node constants

There will be a file called get_node_constants.js and it will only cater to this particular command. Is that ok?

**Comment by shuse2** [comment]
I think we need to think structure of the current commands, too.
For example,
getting information through API is done by
```
get delegates xxx xxx
```
however, it doesnt have nested level like this case `get node constants`.
Also, if we do above command, I haven't figure out how enabling forging status #510 command will be parallel to the get command

**Comment by Mastermaulik** [comment]
Yeah, I had the same doubt.

These three commands can be implemented by the same command => get node xxx
1. get node constants
2. get node forging
3. get node health

Now as the 4th command is a PUT operation, we can have a command like following:
1. edit node forging <publicKey> <decryptionKey>

How does this look like?

**Comment by shuse2** [comment]
It is related to #522, but I was thinking to combine all the node status in one command.
Although it calls different API, considering other CLI API (like pm2 show), it could be controlled by flag how much information we display.

like `node status --all` or `node status --detail` kind of commands
