### ISSUE TITLE
Be consistent on how to define assertion targets

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-commander#464]
### Description

In test, sometimes the assertion target is defined in `when` and `then`.
It should be consistent to be defined in `when` and inserted in the context at the same time.

```
// Bad
const values = ['value', 'values', 123, null, 'aPublicKeyString', '{"more":["publicKey1","publicKey2"]}', 'secretKey1\nsecretKey2'];
return (returnValue[0]).should.eql(values);

// Good
const { returnValue, values } = this.test.ctx;
return (returnValue[0]).should.eql(values);
```

**Comment by willclarktech** [comment]
Better still would be to define them in `given` steps wherever possible.

**Comment by shuse2** [comment]
This is no longer valid after v2.0
