### ISSUE TITLE
Add a command to get node constants

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-commander#508]
### Description

Add a command to get node constants that user is making request to.

child issue of #441

**Comment by Mastermaulik** [comment]
@shuse2 , can you please provide example of what the command would look like? I mean what kind of arguments will the command take?

Also, can you please provide me detail about from where the node information would be coming in from?
From the lisk-elements repo, i saw that we get this.node, do we need to reference this or some different way to get the node details?

**Comment by shuse2** [comment]
I haven't decided good command to do this with combination of enable forging and forging information.

We will use lisk-element function of
```
APIClient().node.getConstants()
```

**Comment by Mastermaulik** [comment]
@shuse2 , thank you for providing information, I would like to work on this feature.

Also, I am facing an issue when trying to run lisk on my pc, I have sent you details on gitter. Can you please reply back to me over gitter?

**Comment by Mastermaulik** [comment]
@shuse2 , I was able to make a call to **api/node/constants** endpoint, and I discovered that the response type is HTML returning 404: Not Found 

Is this endpoint removed?

**Comment by shuse2** [comment]
superseded by #507
