### ISSUE TITLE
Refactor cryptography util

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-commander#516]
**Expected behavior:** We should only use classes where it's necessary to track state. Also we should use consistent naming.

**Actual behavior:** We use a class for our cryptography util, but there's no state to track. This could be refactored to be a set of pure functions. We use `cryptography`, `Crypto` and `liskCrypto`.

### Versions

1.0.0

**Comment by yatki** [comment]
closed by #589
