### ISSUE TITLE
Reorganize the command list 

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-commander#522]
### Description
With the current list of commands, as we add more feature, the command tends to get long,
and there are several conflicts or nesting.

We should reorganize in a way that commands are more extendable.

**Current command list:**
```
help [command...]
exit
broadcast signature [options] [signature]
broadcast transaction [options] [transaction]
config [options]
create account [options]
create transaction cast votes [options]
create transaction register delegate [options] <username>
create transaction register multisignature account [options] <lifetime> <minimum> <keysgroup...>
create transaction register second passphrase [options]
create transaction transfer [options] <amount> <address>
decrypt message [options] <senderPublicKey> <nonce> [message]
decrypt passphrase [options] <iv> [passphrase]
encrypt message [options] <recipient> [message]
encrypt passphrase [options]
get [options] <type> <input>
list [options] <type> <inputs...>
set [options] <variable> <value>
show copyright [options]
show warranty [options]
sign message [options] [message]
verify message [options] <publicKey> <signature> [message]
```

**Proposed command list:**
```
lisk help
lisk warranty
lisk copyright

lisk transaction
	get
	list
	create
	sign
	verify
	broadcast

lisk account
	get
	create

lisk config
	get
	set

lisk passphrase
	decrypt
	encrypt

lisk message
	sign
	verify
	decrypt
	encrypt

lisk signature
	broadcast

lisk block
	get
	list

lisk delegate
	get
	list
```
#### to be implemented
```
lisk voter
	get

lisk vote
	get

lisk block
	create

lisk node
	status
	forging
	upgrade

lisk snapshot
	create
	apply

lisk bootstrap
	create
```

### Versions

1.0.0

**Comment by willclarktech** [comment]
@shuse2 Does this issue also cover expanding the functionality of commands such as `list transactions`, which currently can only query by id?

**Comment by shuse2** [comment]
I think adding functionality for each commands could be done before or after the command change using `options` for list commands where u can specify the queries

**Comment by Mastermaulik** [comment]
@shuse2 , how would command `edit node forging` be listed then?

**Comment by shuse2** [comment]
I was thinking 
`lisk node status` will cover all of the node information.
something like `lisk node status --forging` will additionally show the status of forging, but `lisk node status` will only show basic information.

To enable forging, something like
`lisk node forge 'passphrase' --url 'http://localhost:4000'` might be good?

**Comment by Mastermaulik** [comment]
On a side note, I was thinking about where are the node requests handled because the node endpoint is not part of lisk API.

Where does the Lisk Elements Repo send a GET/PUT request to?

**Comment by shuse2** [comment]
yes publicKey and password for now (I think it still has changes on the latest API though)

**Comment by shuse2** [comment]
With #524, all the commands are reorganized.
