### ISSUE TITLE
Make Lisky handle improper exits

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-commander#523]
### Description

When lisky is not exited correctly, e.g. by closing the window with an active lisky session, the `.lock` file is not cleaned up, and causes the error the next time you try to start lisky.
As this might happen from time to time, I was wondering if there is a way to clean up the .lock file if a session is closed while a lisky process runs on it.

### Steps to Reproduce

1. Open terminal
2. type `lisky`
3. Close terminal
4. Open terminal
5. type `lisky`

**Expected behavior:** 
Lisky should start. Or Lisky should offer an option to recover my old session.

**Actual behavior:** 
The error `Config lockfile at /path/to/lisky/config.lock found. Are you running Lisky in another process?` is thrown.
I need to remove the lock file manually to make it work again.
**Reproduces how often:** 100%
### Versions
macOS

**Comment by shuse2** [comment]
I feel like if we don't have interactive mode, it wouldn't be a problem.
We should discuss as a CLI tool, if we really need the interactive mode or not.

**Comment by willclarktech** [comment]
https://github.com/LiskHQ/lisky/issues/525

**Comment by shuse2** [comment]
This is fixed by #533
