### ISSUE TITLE
Remove interactive mode

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-commander#525]
**Expected behavior:** Lisk Commander should only support non-interactive mode.

**Actual behavior:** We have both non-interactive and interactive mode.

### Versions

1.0.0

This is a discussion issue.

**Comment by shuse2** [comment]
I am all in favour of removing interactive mode!

**Comment by willclarktech** [comment]
We should seek feedback from the community to see if anyone is strongly in favour of keeping it.

**Comment by shuse2** [comment]
Closing because we move to `oclif` on `v2.0` and it doesn't support interactive mode
