### ISSUE TITLE
Update Doc for create an account

### ISSUE THREAD

**Issue by guillaumeLamanda** [LiskHQ/lisk-commander#579]
Hi 👋 

### Description
I was trying to create a testnet account with Lisk Commander. It is not clear that the account is not immediatly created on the network. You need to send LSK to an other account to confirm the **publicKey**. 
I understood it only after a day of trying, when I found [this answer from slaweet](https://github.com/LiskHQ/lisk-nano/issues/1043#issuecomment-365845974)

### Steps to Reproduce
1. Launch lisk commander : `lisk`
2. Set api.network to "test"
3. Create an account

**Expected behavior:** 
- [Testnet explorer](https://testnet-explorer.lisk.io/) to find the address (because on the mainnet with the HUB, it do find it. This is a bit disruptive)
OR
- Explicitly say on the doc the step to reproduce to activate the account

**Actual behavior:** 
- Testnet explorer say : "No matching record found" 

**Reproduces how often:** 100%

### Version 
lisk-commander@next

I know there is huge changes between 0.9 and 1.0.0 version, and, for exemple, the HUB is break with the testnet. This might be related.

Anyway, thanks for all the work you are doing !

**Comment by willclarktech** [comment]
@guillaumeLamanda If the address has never appeared in the blockchain, what were you expecting explorer to tell you?

**Comment by guillaumeLamanda** [comment]
I was first thinking that account creation was a transaction. 
I Then I realized I wasn't gonna broadcast it.
All I'm saying is that make it appear in the documentation can help. This is just a feedback. 

But I can't explain myself why the mainnet hub can find it. Someone have already created this address on the mainnet ? 

Feel free to close it if you don't think it is relevent.

**Comment by shuse2** [comment]
If you try to create an account in the hub, and check the explorer, u will get the same result.
Create account is a generation of account, which does not exist in the blockchain.

Also, when you create an account, you have no LSK in it, so you cannot create a transaction.

I will close it as invalid because this behaviour cannot be changed.
