### ISSUE TITLE
When lisk-commander support create white label sidechain or any roadmap about it?

### ISSUE THREAD

**Issue by jerry-sl** [LiskHQ/lisk-commander#583]
I just read document on [lisk.io](https://lisk.io/products), there says:

> 

>  1. Generate your own white label sidechain
You've made the decision to build your own blockchain application with Lisk, congratulations! **As soon as our sidechain modules for Lisk Commander become available,** you will be able to use the command line interface to easily conduct sidechain development.

> Lisk Commander will help you create a cryptographically-secure genesis block or bundle vital sidechain components. These components include Lisk Core's essentials, such as an efficient P2P WebSocket transport layer or a standardized account ledger system.

I can't help waiting to create a white label sidechain on top of Lisk, but I didn't find doc or demo about how to do.

**Comment by shuse2** [comment]
Hello, thank you for raising the question.
Currently, we do not have the sidechain mechanism yet.
Therefore, it is still not possible to do so, but it's definitely the vision that we want to achieve.

As for the roadmap, we are making effort to build one now.
Please follow our official blogs for the updates.
