### ISSUE TITLE
README.md: "You will need version 6.11.x or higher" is incorrect.

### ISSUE THREAD

**Issue by johnalexhebert** [LiskHQ/lisk-commander#610]
### Description

READ.md states "You will need version 6.11.x or higher" of nodejs. Using any version after 6.14 does not work.

Also note that https://lisk.io/documentation/lisk-commander/setup#pre-installation does state:
> Not Supported
> Platforms without NodeJS version between 6.12 and 6.14

### Fix
Update README.md to state something like:
"You will need nodejs version 6.11.x <> 6.14.x."

**Comment by willclarktech** [comment]
This issue should also address the inconsistency on the linked documentation page. It also says:

```
You will need version 6.14.1.
```
