### ISSUE TITLE
Command throws an error when connecting with pipe

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-commander#620]
### Description

When connecting the commands with pipe after the command, it will throws an error

`./bin/run transaction:sign '{"type":0,"timestamp":123,"senderPublicKey":"abcd1234","amount":"100","asset":{}}' | echo`

```
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions

2.0-

**Comment by shuse2** [comment]
Related issue on oclif
https://github.com/oclif/command/issues/34

**Comment by willclarktech** [comment]
This issue should solve this: https://github.com/LiskHQ/lisk-commander/pull/577#discussion_r218075246

**Comment by mitsujutsu** [comment]
Reopened due to unaccounted race condition.
